### ISSUE TITLE
[Question] Why using email to associate records with a user?

### ISSUE THREAD

**Issue by olivierobert** [pramote-chopaka/nimble-web-assignment#19]
## Issue

Both `submission` and `keywordResult` entities store the user's email as in the column `created_by` 🤔 

Wouldn't be better to:
1.  Store the user ID (since this will be unique and immutable)?
2. Store the submission ID to associate a `keyword_result`with a `submission`? In terms of authorization, submissions would already be scoped to a user, so associating each `keywordResult` with a user seems unnecessary.

**Comment by pramote-chopaka** [comment]
1. User ID is UUID and user is stored in different database, I think it would be clearer to store it as email. Keycloak doesn't allow user registration with the same email (username) anyway.
2. Because I'd like to avoid joining to `submission` table when querying `keyword_result`. Without `created_by` in `keyword_result`, to know if the user is authorized, joining with `submission` is required.

**Comment by olivierobert** [comment]
In that case, it seems that using a separate authentication solution (Keycloak), hence the separate storage of user data, might have influenced the architecture decisions in the database. Instead, the domain modeling should preferably not be dictated by third-party tools as these can be swapped. 

If we were to build an ERD diagram of the domain:
- Using the primary key for referencing associations is standard, regardless of the format (BIGINT or UUID). 
- Since `keyword_result` belongs to a `submission`, the foreign key to the submission ID would also be expected. Joining tables is efficient and in most cases (unless we talk about millions of records) do no present performance issues. 

While Keycloak does not allow users to register with the same email, a user can update their email address. In that case, it would require to update all associated records 😨

**Comment by pramote-chopaka** [comment]
I probably overlooked updating user's email scenarios, those seem valid.
I've updated the code to use user ID instead of email. 
The changes are:
- Store user's UUID to `created_by` and `update_by` columns
- Join `submission` table when getting `keyword_result` data
- Remove auditable columns (`created_by`, `created_date`, `modified_by` and `modified_date`) from `keyword_result` table since logic has changed to join with `submission` table instead. Those columns are no longer useful.
- Created by and modified by values are no longer displayed on any screens since it doesn't make sense to show user's UUID

Since there are quite a lot of impacts to the app and database schema (old schema/data need to be dropped before running the new code), I haven't merged the changed to `main` yet. You can merge it when are ready to test it.

**Comment by olivierobert** [comment]
I am not familiar with Keycloak 😅 but the code does seems to use the user ID 👍
